### ISSUE TITLE
Reincluding unarchived packages

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/GraphicalModels#4]
It would be good if you could check from time to time whether packages that were archived on CRAN at some point have been resurrected and would still be suitable for inclusion in the task view. As the list is not so long I did this quickly for all packages in `GraphicalModels` and it seems that these could be included again:

* `abn`
* `catnet`
* `deal`
* `gRc`
* `gRim`
* `MXM`
* `ndtv`

**Comment by hojsgaard** [comment]
Agree. I would like to do this (semi-)automatically though - just not sure how.
Best
Søren



-----Original Message-----
From: Achim Zeileis ***@***.******@***.***%3e>>
Reply-To: cran-task-views/GraphicalModels ***@***.******@***.***%3e>>
To: cran-task-views/GraphicalModels ***@***.******@***.***%3e>>
Cc: Subscribed ***@***.******@***.***%3e>>
Subject: [cran-task-views/GraphicalModels] Reincluding unarchived packages (Issue #4)
Date: Mon, 14 Mar 2022 04:45:30 -0700


It would be good if you could check from time to time whether packages that were archived on CRAN at some point have been resurrected and would still be suitable for inclusion in the task view. As the list is not so long I did this quickly for all packages in GraphicalModels and it seems that these could be included again:

  *   abn
  *   catnet
  *   deal
  *   gRc
  *   gRim
  *   MXM
  *   ndtv

**Comment by zeileis** [comment]
It cannot be done fully automatically because adapting the task view text is often non-trivial. This is what the maintainers should do.

We're planning on improving the situation, though, see:
https://github.com/cran-task-views/ctv/issues/20

**Comment by hojsgaard** [comment]
I thought about the other way around: Given an .md file with package names in it, I wanted to

check that each package is a alive on cran
check if the package has vignettes
extract the description field (because the text I use is a subset of the description field)

Thought that could be done with rvest. The only package I know for "webscraping". Better ideas?

Best Søren


-----Original Message-----
From: Achim Zeileis ***@***.******@***.***%3e>>
Reply-To: cran-task-views/GraphicalModels ***@***.******@***.***%3e>>
To: cran-task-views/GraphicalModels ***@***.******@***.***%3e>>
Cc: Søren Højsgaard ***@***.******@***.***%3e>>, Comment ***@***.******@***.***%3e>>
Subject: Re: [cran-task-views/GraphicalModels] Reincluding unarchived packages (Issue #4)
Date: Mon, 14 Mar 2022 07:54:03 -0700


It cannot be done fully automatically because adapting the task view text is often non-trivial. This is what the maintainers should do.

We're planning on improving the situation, though, see:
cran-task-views/ctv#20<https://github.com/cran-task-views/ctv/issues/20>

**Comment by zeileis** [comment]
For checking that all packages in an .md are on CRAN you can do

    ctv::check_ctv_packages("GraphicalModels.md")

which internally calls `available.packages()` to find out the packages that are available on CRAN.

For more information from the packages, including the description, you can use something like

    db <- tools::CRAN_package_db()[, c("Package", "Description")]

see: https://stackoverflow.com/questions/11560865/list-and-description-of-all-packages-in-cran-from-within-r

And for querying the number and names of vignettes there is no nice solution available, it's probably best to check whether `vignettes/index.rds` exists and read it if available, e.g.,

```
f <- gzcon(url("https://CRAN.R-project.org/web/packages/sandwich/vignettes/index.rds", open = "rb"))
readRDS(f)
##                PDF
## 1  sandwich-CL.pdf
## 2 sandwich-OOP.pdf
## 3     sandwich.pdf
##                                                                                          Title
## 1 Various Versatile Variances: An Object-Oriented Implementation of Clustered Covariances in R
## 2                                           Object-Oriented Computation of Sandwich Estimators
## 3                           Econometric Computing with HC and HAC Covariance Matrix Estimators
close(f)
```

See also: https://stackoverflow.com/questions/10825963/available-cran-vignettes

**Comment by zeileis** [comment]
It would be great if you could address the original issue (reincluding several unarchived packages) because I think that the readers of the task view would profit from it. I don't think that waiting for a (more) automated solution would be the best way forward here.

**Comment by hojsgaard** [comment]
Done

**Comment by zeileis** [comment]
Perfect, thanks, updated on CRAN now.
